### ISSUE TITLE
Installs fine on VS2015 but still doesn't work

### ISSUE THREAD

**Issue by WMeldon** [markrendle/nogit#6]
Not sure if work getting it functional has started or not, but I just tried it and the git plugin still wouldn't go away.  Would love to get this working.

**Comment by randomascii** [comment]
I believe that the git plugin will still show up as being selected, but won't do anything. Watch for CPU usage - that should be gone.

That said, I just installed it myself and I don't know yet whether it works. A VS 2015 installer to simplify the process would be great.

**Comment by randomascii** [comment]
Also, see this bug and consider voting it up:
https://connect.microsoft.com/VisualStudio/feedback/details/1885411/microsoft-git-provider-source-control-plug-in-consumes-much-cpu-time-wont-stay-disabled

**Comment by WMeldon** [comment]
CPU usage wasn't really my concern, I'm more interested being able to use TFS in Visual Studio even if it is technically also a git repository.  I've only found a few other people with that use case sadly.

**Comment by markrendle** [comment]
I've just published 1.3 on the Marketplace with full support for VS2013, 2015 and 2017; assuming that closes this issue.
